name: Documentation

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  doxygen:
    name: "Doxygen"
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7

      - run: mkdir build

      - uses: actions/setup-python@v7
        with:
          python-version: 3.14

      - run: pip install \
          build \
          py-build-cmake \
          pybind11 \
          pybind11-stubgen \
          pybind11-mkdoc \
          clang

      - run: sudo apt-get install -y doxygen

      - run: ./tools/generate-docs.sh

      - uses: actions/upload-artifact@v7
        with:
          name: documentation
          path: build/html
